In [1]:
import numpy as np
from google.colab import files

In [2]:
uploaded = files.upload()

Saving p3_train.csv to p3_train.csv


In [3]:
# Get the uploaded file name
file_name = next(iter(uploaded))

# Load the CSV file using NumPy
data_train = np.genfromtxt(file_name, delimiter=',')

In [4]:
data_train

array([[-0.66524016, -1.44494482, -0.50279241, ..., -0.51264941,
         1.14855255,  1.        ],
       [ 2.77439505,  1.60670577,  0.55340908, ..., -0.3560387 ,
         0.67794381,  1.        ],
       [-0.62586937, -0.26507389,  0.70141731, ...,  0.10409147,
        -0.98485438,  5.        ],
       ...,
       [-1.7652821 , -0.13820513, -2.05887396, ..., -0.16761556,
         1.92810659,  5.        ],
       [ 1.31672603,  0.29958778,  0.40964062, ..., -0.50250074,
        -0.77139579,  2.        ],
       [ 0.41895968,  1.06039492, -1.1435325 , ...,  1.16254537,
         0.12443366,  4.        ]])

In [5]:
np.shape(data_train)

(60000, 11)

In [6]:
n1=0
n2=0
n3=0
n4=0
n5=0
for i in range(0,60000):
  if data_train[i][10]==1:
    n1=n1+1
  if data_train[i][10]==2:
    n2=n2+1
  if data_train[i][10]==3:
    n3=n3+1
  if data_train[i][10]==4:
    n4=n4+1
  if data_train[i][10]==5:
    n5=n5+1


In [7]:
n1

12029

In [8]:
p1=n1/60000
p2=n2/60000
p3=n3/60000
p4=n4/60000
p5=n5/60000

In [9]:
p1

0.20048333333333335

In [10]:
x1=np.zeros((n1,10))
x2=np.zeros((n2,10))
x3=np.zeros((n3,10))
x4=np.zeros((n4,10))
x5=np.zeros((n5,10))

In [11]:
np.shape(x1)

(12029, 10)

In [12]:
k1=0
k2=0
k3=0
k4=0
k5=0

for i in range(0,60000):
    if data_train[i][10]==1:
      for j in range(0,10):
        x1[k1][j]=data_train[i][j]
      k1=k1+1
    elif data_train[i][10]==2:
      for j in range(0,10):
        x2[k2][j]=data_train[i][j]
      k2=k2+1
    elif data_train[i][10]==3:
      for j in range(0,10):
        x3[k3][j]=data_train[i][j]
      k3=k3+1
    elif data_train[i][10]==4:
      for j in range(0,10):
        x4[k4][j]=data_train[i][j]
      k4=k4+1
    elif data_train[i][10]==5:
      for j in range(0,10):
        x5[k5][j]=data_train[i][j]
      k5=k5+1

In [13]:
x1

array([[-0.66524016, -1.44494482, -0.50279241, ..., -0.43669382,
        -0.51264941,  1.14855255],
       [ 2.77439505,  1.60670577,  0.55340908, ...,  1.85333769,
        -0.3560387 ,  0.67794381],
       [-0.51502036,  0.19890526,  0.54183173, ..., -0.72564118,
         0.25187396, -0.43100653],
       ...,
       [-1.20204078, -0.51212793, -0.76522766, ...,  0.65873833,
        -2.02105334, -0.19591757],
       [-0.54578945,  0.84513346, -0.69664901, ...,  1.40517791,
        -0.07249937,  0.23566335],
       [-1.46128873, -0.91149415, -0.18040443, ...,  0.77853778,
        -0.13012596, -0.94027375]])

In [14]:
def MU(arr,size):
  mu=np.zeros((10,1))
  for i in range(0,size):
    for j in range(0,10):
      mu[j]=mu[j]+arr[i][j]
  return mu/size

In [15]:
mu1=MU(x1,n1)
mu2=MU(x2,n2)
mu3=MU(x3,n3)
mu4=MU(x4,n4)
mu5=MU(x5,n5)

In [16]:
mu1

array([[ 2.02703067e-01],
       [ 1.20997361e+00],
       [ 1.81973642e-02],
       [-9.25991531e-03],
       [ 3.11968850e-04],
       [ 6.19575501e-03],
       [ 1.64881781e-03],
       [ 1.04556667e-02],
       [ 2.91771113e-03],
       [ 2.12628967e-02]])

In [34]:
def sgma(arr,size,mu):
  sigma=np.zeros((10,10))
  diff=np.zeros((10,1))
  for i in range(0,size):
    for j in range(0,10):
      diff[j]=(arr[i][j]-mu[j])
    sigma=sigma+(diff@(diff.T))
    diff=np.zeros((10,1))
  return sigma/size

In [35]:
sigma1=sgma(x1,n1,mu1)
sigma2=sgma(x2,n2,mu2)
sigma3=sgma(x3,n3,mu3)
sigma4=sgma(x4,n4,mu4)
sigma5=sgma(x5,n5,mu5)


In [19]:
sigma1

array([[ 2.36759500e+00,  1.18392879e+00, -1.28365482e-02,
         6.66536575e-03, -2.06539424e-02, -2.95117943e-02,
         4.17361850e-03, -1.98253263e-03, -1.87639371e-02,
        -1.50809643e-02],
       [ 1.18392879e+00,  2.39667879e+00, -1.06127541e-02,
        -7.15520071e-03, -6.45529295e-03, -1.45744219e-02,
         7.47295583e-03, -2.28001268e-02, -3.79157763e-02,
        -2.63615188e-02],
       [-1.28365482e-02, -1.06127541e-02,  1.21735548e+00,
         2.75304221e-02,  1.47021593e-02,  7.16665253e-04,
        -3.59319606e-03,  2.04760937e-02, -5.03535472e-03,
        -8.64859712e-03],
       [ 6.66536575e-03, -7.15520071e-03,  2.75304221e-02,
         1.19307209e+00,  8.18518196e-03,  2.77391344e-03,
        -1.28294556e-02,  5.76193872e-03,  5.15781495e-03,
        -9.30218287e-03],
       [-2.06539424e-02, -6.45529295e-03,  1.47021593e-02,
         8.18518196e-03,  1.17053694e+00,  7.22069400e-03,
         5.32630759e-03, -1.39356723e-02, -6.12251159e-03,
        -4.

In [36]:
lambda1=np.linalg.inv(sigma1)
lambda2=np.linalg.inv(sigma2)
lambda3=np.linalg.inv(sigma3)
lambda4=np.linalg.inv(sigma4)
lambda5=np.linalg.inv(sigma5)


In [21]:
np.linalg.det(np.linalg.inv(lambda1))

17.243836831315935

In [22]:
import math

In [23]:
math.pi

3.141592653589793

In [24]:
def class_density(mu,Lambda,data):
  diff=np.zeros((10,1))
  for i in range(0,10):
    diff[i]=data[i]-mu[i]
  e=-0.5*((diff.T)@Lambda@diff)
  evalue=math.exp(e)
  sigma=np.linalg.inv(Lambda)
  #value=1/(((2*(math.pi))**5)*math.sqrt(np.linalg.det(sigma)))
  det=math.sqrt(np.linalg.det(sigma))
  value=(2*math.pi)**5
  return evalue/(det*value)

In [25]:
uploaded1 = files.upload()

Saving p3_test.csv to p3_test.csv


In [26]:
# Get the uploaded file name
file_name1 = next(iter(uploaded1))

# Load the CSV file using NumPy
data_test = np.genfromtxt(file_name1, delimiter=',')

In [27]:
np.shape(data_test)

(15000, 11)

In [28]:
data_train[0]

array([-0.66524016, -1.44494482, -0.50279241, -1.12577976, -0.45391642,
       -0.25270986, -0.82476845, -0.43669382, -0.51264941,  1.14855255,
        1.        ])

In [70]:
def density_calculator(data,m,mu1,mu2,mu3,mu4,mu5,lambda1,lambda2,lambda3,lambda4,lambda5):
  post=np.zeros((m,5))
  for i in range(0,m):
      post[i][0]=class_density(mu1,lambda1,data[i])
      post[i][1]=class_density(mu2,lambda2,data[i])
      post[i][2]=class_density(mu3,lambda3,data[i])
      post[i][3]=class_density(mu4,lambda4,data[i])
      post[i][4]=class_density(mu5,lambda5,data[i])
  return post

In [71]:
X_test=np.zeros((15000,10))
for i in range(0,15000):
  for j in range(0,10):
    X_test[i][j]=data_test[i][j]

In [72]:
post=density_calculator(X_test,15000,mu1,mu2,mu3,mu4,mu5,lambda1,lambda2,lambda3,lambda4,lambda5)

In [73]:
post

array([[2.03048698e-08, 7.26261268e-08, 2.09094937e-08, 1.10238659e-06,
        1.52289710e-08],
       [8.24667942e-08, 4.56596999e-07, 6.00194773e-08, 1.32491323e-07,
        2.27490160e-06],
       [2.31689940e-08, 2.83825542e-07, 1.45968060e-07, 1.18087516e-07,
        5.90679209e-08],
       ...,
       [5.88820015e-10, 2.78495266e-10, 5.67092089e-09, 6.64974954e-08,
        4.51294909e-10],
       [1.21438047e-07, 2.07088686e-07, 2.91786924e-07, 1.71177084e-07,
        3.34487372e-08],
       [3.36717990e-07, 7.96841962e-08, 2.17023264e-08, 1.03036844e-07,
        1.25075264e-07]])

In [37]:
np.shape(post)

(15000, 5)

In [74]:
def classifier1(post,p1,p2,p3,p4,p5):
  cls=np.zeros((15000,1))
  a=np.zeros((5,1))
  for i in range(0,15000):
    a[0]=p1*post[i][0]
    a[1]=p2*post[i][1]
    a[2]=p3*post[i][2]
    a[3]=p4*post[i][3]
    a[4]=p5*post[i][4]
    cls[i]=np.argmax(a)+1
    a=np.zeros((5,1))
  return cls

In [75]:
cls1=classifier1(post,p1,p2,p3,p4,p5)

In [76]:
data_test

array([[-0.36155998, -0.07137044,  0.32634803, ...,  0.12132694,
        -0.21378723,  2.        ],
       [ 0.87320572, -0.68542094, -1.0513115 , ...,  1.43991457,
         2.04474109,  1.        ],
       [ 0.9848795 , -1.44588972, -0.35913845, ..., -0.8675261 ,
        -1.21703136,  5.        ],
       ...,
       [ 0.28527298,  1.00770785, -0.31063534, ..., -0.36555153,
         0.71625022,  4.        ],
       [-1.05595651, -0.14687865, -0.47438609, ..., -0.10981379,
        -1.84707061,  2.        ],
       [-0.84914776,  2.09934799, -1.33686243, ..., -0.48751575,
         1.25954515,  1.        ]])

In [77]:
y_test=np.zeros((15000,1))
for i in range(0,15000):
  y_test[i]=data_test[i][10]



In [78]:
def accuracy(arr1,arr2):
  count=0
  for i in range(0,15000):
    if arr1[i]-arr2[i]==0:
      count=count+1
  return count/15000


In [82]:
accuracy=accuracy(y_test,cls1)

In [83]:
accuracy

0.5938666666666667