In [1]:
import pandas as pd
import numpy as np


In [3]:
from google.colab import files
uploaded = files.upload()

Saving p3_train.csv to p3_train.csv


In [30]:
# Get the uploaded file name
file_name = next(iter(uploaded))

# Load the CSV file using NumPy
data_train = np.genfromtxt(file_name, delimiter=',')

In [31]:
data_train

array([[-0.66524016, -1.44494482, -0.50279241, ..., -0.51264941,
         1.14855255,  1.        ],
       [ 2.77439505,  1.60670577,  0.55340908, ..., -0.3560387 ,
         0.67794381,  1.        ],
       [-0.62586937, -0.26507389,  0.70141731, ...,  0.10409147,
        -0.98485438,  5.        ],
       ...,
       [-1.7652821 , -0.13820513, -2.05887396, ..., -0.16761556,
         1.92810659,  5.        ],
       [ 1.31672603,  0.29958778,  0.40964062, ..., -0.50250074,
        -0.77139579,  2.        ],
       [ 0.41895968,  1.06039492, -1.1435325 , ...,  1.16254537,
         0.12443366,  4.        ]])

In [32]:
n1=0
n2=0
n3=0
n4=0
n5=0
for i in range(0,60000):
  if data_train[i][10]==1:
    n1=n1+1
  if data_train[i][10]==2:
    n2=n2+1
  if data_train[i][10]==3:
    n3=n3+1
  if data_train[i][10]==4:
    n4=n4+1
  if data_train[i][10]==5:
    n5=n5+1

In [33]:
X_train=data_train[:,0:10]
y_train=data_train[:,-1]

In [34]:
X_train

array([[-0.66524016, -1.44494482, -0.50279241, ..., -0.43669382,
        -0.51264941,  1.14855255],
       [ 2.77439505,  1.60670577,  0.55340908, ...,  1.85333769,
        -0.3560387 ,  0.67794381],
       [-0.62586937, -0.26507389,  0.70141731, ...,  1.2385759 ,
         0.10409147, -0.98485438],
       ...,
       [-1.7652821 , -0.13820513, -2.05887396, ...,  0.28859359,
        -0.16761556,  1.92810659],
       [ 1.31672603,  0.29958778,  0.40964062, ...,  0.25653821,
        -0.50250074, -0.77139579],
       [ 0.41895968,  1.06039492, -1.1435325 , ...,  3.01004262,
         1.16254537,  0.12443366]])

In [10]:
y_train

array([1., 1., 5., ..., 5., 2., 4.])

In [35]:
def max_min(data,m,n):
  max=np.zeros((10,1))
  min=np.zeros((10,1))
  for i in range(0,n-1):
    max[i]=np.max(data[:,i])
    min[i]=np.min(data[:,i])
  return max,min



In [36]:
def normalize(data,m,n):
  max,min=max_min(data,m,n)
  data_normalized=data
  for i in range(0,m):
    for j in range(0,n-1):
      data_normalized[i][j]=(data[i][j]-min[j])/(max[j]-min[j])
  return data_normalized


In [28]:
def vrest1(data,size):
  mat1=np.copy(data)
  for i in range(0,size):
    if mat1[i][10]!=1:
      mat1[i][10]=-1
  return mat1

def vrest2(data,size):
  mat2=np.copy(data)
  for i in range(0,size):
    if mat2[i][10]==2:
      mat2[i][10]=1
    else:
      mat2[i][10]=-1
  return mat2

In [29]:
def vrest3(data,size):
  mat3=np.copy(data)
  for i in range(0,size):
    if mat3[i][10]==3:
      mat3[i][10]=1
    else:
      mat3[i][10]=-1
  return mat3

def vrest4(data,size):
  mat4=np.copy(data)
  for i in range(0,size):
    if mat4[i][10]==4:
      mat4[i][10]=1
    else:
      mat4[i][10]=-1
  return mat4

def vrest5(data,size):
  mat5=np.copy(data)
  for i in range(0,size):
    if mat5[i][10]==5:
      mat5[i][10]=1
    else:
      mat5[i][10]=-1
  return mat5

In [15]:
X_train_Norm=normalize(data_train,60000,11)

In [ ]:
X_train_Norm

array([[0.41561724, 0.25532628, 0.44478438, ..., 0.4218294 , 0.51466103,
        1.        ],
       [0.72591991, 0.52263612, 0.54157416, ..., 0.43654057, 0.47812012,
        1.        ],
       [0.41916903, 0.35867727, 0.55513756, ..., 0.47976271, 0.34901041,
        5.        ],
       ...,
       [0.31637825, 0.36979036, 0.30218585, ..., 0.45424002, 0.57519033,
        5.        ],
       [0.594418  , 0.4081389 , 0.52839929, ..., 0.42278271, 0.36558462,
        2.        ],
       [0.51342706, 0.47478193, 0.38606728, ..., 0.57918815, 0.43514224,
        4.        ]])

In [41]:
data_train

array([[-0.66524016, -1.44494482, -0.50279241, ..., -0.51264941,
         1.14855255,  1.        ],
       [ 2.77439505,  1.60670577,  0.55340908, ..., -0.3560387 ,
         0.67794381,  1.        ],
       [-0.62586937, -0.26507389,  0.70141731, ...,  0.10409147,
        -0.98485438,  5.        ],
       ...,
       [-1.7652821 , -0.13820513, -2.05887396, ..., -0.16761556,
         1.92810659,  5.        ],
       [ 1.31672603,  0.29958778,  0.40964062, ..., -0.50250074,
        -0.77139579,  2.        ],
       [ 0.41895968,  1.06039492, -1.1435325 , ...,  1.16254537,
         0.12443366,  4.        ]])

In [38]:
mat1=vrest1(data_train,60000)

In [39]:
mat1

array([[-0.66524016, -1.44494482, -0.50279241, ..., -0.51264941,
         1.14855255,  1.        ],
       [ 2.77439505,  1.60670577,  0.55340908, ..., -0.3560387 ,
         0.67794381,  1.        ],
       [-0.62586937, -0.26507389,  0.70141731, ...,  0.10409147,
        -0.98485438, -1.        ],
       ...,
       [-1.7652821 , -0.13820513, -2.05887396, ..., -0.16761556,
         1.92810659, -1.        ],
       [ 1.31672603,  0.29958778,  0.40964062, ..., -0.50250074,
        -0.77139579, -1.        ],
       [ 0.41895968,  1.06039492, -1.1435325 , ...,  1.16254537,
         0.12443366, -1.        ]])

In [43]:
mat2=vrest2(data_train,60000)
mat3=vrest3(data_train,60000)
mat4=vrest4(data_train,60000)
mat5=vrest5(data_train,60000)

In [45]:
np.shape(mat3)

(60000, 11)

In [48]:
mat5

array([[-0.66524016, -1.44494482, -0.50279241, ..., -0.51264941,
         1.14855255, -1.        ],
       [ 2.77439505,  1.60670577,  0.55340908, ..., -0.3560387 ,
         0.67794381, -1.        ],
       [-0.62586937, -0.26507389,  0.70141731, ...,  0.10409147,
        -0.98485438,  1.        ],
       ...,
       [-1.7652821 , -0.13820513, -2.05887396, ..., -0.16761556,
         1.92810659,  1.        ],
       [ 1.31672603,  0.29958778,  0.40964062, ..., -0.50250074,
        -0.77139579, -1.        ],
       [ 0.41895968,  1.06039492, -1.1435325 , ...,  1.16254537,
         0.12443366, -1.        ]])

In [51]:
a=np.ones((60000,1))

In [62]:

mat_cls1=np.concatenate((a,mat1),axis=1)
mat_cls2=np.concatenate((a,mat2),axis=1)
mat_cls3=np.concatenate((a,mat3),axis=1)
mat_cls4=np.concatenate((a,mat4),axis=1)
mat_cls5=np.concatenate((a,mat5),axis=1)

In [53]:

np.shape((mat_cls1))

(60000, 12)

In [54]:
mat_cls1

array([[ 1.        , -0.66524016, -1.44494482, ..., -0.51264941,
         1.14855255,  1.        ],
       [ 1.        ,  2.77439505,  1.60670577, ..., -0.3560387 ,
         0.67794381,  1.        ],
       [ 1.        , -0.62586937, -0.26507389, ...,  0.10409147,
        -0.98485438, -1.        ],
       ...,
       [ 1.        , -1.7652821 , -0.13820513, ..., -0.16761556,
         1.92810659, -1.        ],
       [ 1.        ,  1.31672603,  0.29958778, ..., -0.50250074,
        -0.77139579, -1.        ],
       [ 1.        ,  0.41895968,  1.06039492, ...,  1.16254537,
         0.12443366, -1.        ]])

In [60]:
X_train1=mat_cls1[:,0:11]
y_train1=mat_cls1[:,-1]


In [58]:
X_train1

array([[ 1.        , -0.66524016, -1.44494482, ..., -0.43669382,
        -0.51264941,  1.14855255],
       [ 1.        ,  2.77439505,  1.60670577, ...,  1.85333769,
        -0.3560387 ,  0.67794381],
       [ 1.        , -0.62586937, -0.26507389, ...,  1.2385759 ,
         0.10409147, -0.98485438],
       ...,
       [ 1.        , -1.7652821 , -0.13820513, ...,  0.28859359,
        -0.16761556,  1.92810659],
       [ 1.        ,  1.31672603,  0.29958778, ...,  0.25653821,
        -0.50250074, -0.77139579],
       [ 1.        ,  0.41895968,  1.06039492, ...,  3.01004262,
         1.16254537,  0.12443366]])

In [61]:
y_train1

array([ 1.,  1., -1., ..., -1., -1., -1.])

In [64]:
X_train2=mat_cls2[:,0:11]
y_train2=mat_cls2[:,-1]
X_train3=mat_cls3[:,0:11]
y_train3=mat_cls3[:,-1]
X_train4=mat_cls4[:,0:11]
y_train4=mat_cls4[:,-1]
X_train5=mat_cls5[:,0:11]
y_train5=mat_cls5[:,-1]



In [69]:
def w_star(A,y_train):
  W_star=np.zeros((11,1))
  W_star=(np.linalg.inv((A.T)@A))@(A.T)@y_train
  return W_star



In [70]:
W_star1=w_star(X_train1,y_train1)
W_star2=w_star(X_train2,y_train2)
W_star3=w_star(X_train3,y_train3)
W_star4=w_star(X_train4,y_train4)
W_star5=w_star(X_train5,y_train5)

In [83]:
W_star1

array([-0.56922004, -0.00058638,  0.21874155, -0.00557447, -0.06570336,
       -0.01649415, -0.06783803, -0.00890344, -0.06398231, -0.01049051,
       -0.06298499])

In [72]:
np.shape(W_star1)

(11,)

In [73]:
uploaded1 = files.upload()

Saving p3_test.csv to p3_test.csv


In [74]:
# Get the uploaded file name
file_name1 = next(iter(uploaded1))

# Load the CSV file using NumPy
data_test = np.genfromtxt(file_name1, delimiter=',')

In [75]:
a=np.ones((15000,1))
mat=np.concatenate((a,data_test),axis=1)

In [76]:
X_test=mat[:,0:11]
y_test=mat[:,-1]

In [94]:
W_star1=np.reshape(W_star1,(11,1))
W_star2=np.reshape(W_star2,(11,1))
W_star3=np.reshape(W_star3,(11,1))
W_star4=np.reshape(W_star4,(11,1))
W_star5=np.reshape(W_star5,(11,1))


In [93]:
np.shape(W_star1)

(11, 1)

In [99]:
mat1=X_test@W_star1
mat2=X_test@W_star2
mat3=X_test@W_star3
mat4=X_test@W_star4
mat5=X_test@W_star5
M=np.concatenate((mat1,mat2,mat3,mat4,mat5),axis=1)
y=np.zeros((15000,1))
for i in range(0,15000):
  y[i]=(np.argmax(M[i]))+1





In [97]:
np.shape(y)

(15000, 1)

In [100]:
sum=0
for i in range(0,15000):
  if y[i]-y_test[i]==0:
    sum=sum+1

In [101]:
accuracy=sum/15000

In [102]:
accuracy

0.5708